AWSTemplateFormatVersion: '2010-09-09'
Description: 'demo cfn-nag'

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hello

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: sid
            Effect: Allow
            Principal:
              AWS: '*'
            Action: ['s3:GetObject']
            Resource: [!Sub 'arn:aws:s3:::${Bucket}/*']
